services:
  tools:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../data:/app/data
      - ../output:/app/output

  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../data:/app/data
      - ../output:/app/output
